In [ ]:
!pip install mxnet gluoncv

  Using cached https://files.pythonhosted.org/packages/29/bb/54cbabe428351c06d10903c658878d29ee7026efbe45133fd133598d6eb6/mxnet-1.7.0.post1-py2.py3-none-manylinux2014_x86_64.whl
     |████████████████████████████████| 819kB 2.7MB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


***2.1 Data Manipulation***


In [ ]:
# numpy compatible mxnet
from mxnet import np, npx
npx.set_np()

In [ ]:
# create a vector ranging from 0 to 12.
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# each dimensions shape
x.shape

(12,)

In [ ]:
# total elements
x.size

12

In [ ]:
# reshape the 12 elements without changing them.
X = x.reshape(3, 4)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# a tensor of zeroes.
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# sample from a gaussian(normal) distribution with a mean of 0 and std of 1.
np.random.normal(0, 1, size=(3, 4))

array([[ 2.2122064 ,  1.1630787 ,  0.7740038 ,  0.4838046 ],
       [ 1.0434403 ,  0.29956347,  1.1839255 ,  0.15302546],
       [ 1.8917114 , -1.1688148 , -1.2347414 ,  1.5580711 ]])

In [ ]:
# elementwise exp of the x matrix.
np.exp(x)

array([1.0000000e+00, 2.7182817e+00, 7.3890562e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342880e+02, 1.0966332e+03,
       2.9809580e+03, 8.1030840e+03, 2.2026465e+04, 5.9874141e+04])

In [ ]:
# concatenation of different axes.
X = np.arange(12).reshape(3, 4)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
# elementwise comparison.
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# sum over all elements.
X.sum()

array(66.)

In [ ]:
# The broadcasting mechanism. (good or bad?)
a = np.arange(3).reshape(3,1)
b = np.arange(2).reshape(1,2)
a, b

(array([[0.],
        [1.],
        [2.]]), array([[0., 1.]]))

In [ ]:
# both arrays were extended to match each others sizes..
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

In [ ]:
# indexing done, as normal with np arrays.
X[-1], X[1:3]

(array([ 8.,  9., 10., 11.]), array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [ ]:
# change a single element
X[1, 2] = 9
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# changing whole rows.
X[0:2, :] = 12
X

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# a new memory space is allocated each time.
before = id(Y)
Y = Y + X
id(Y) == before

False

In [ ]:
# wont happen if done this way.
before = id(Y)
Y += X
id(Y) == before

True

In [ ]:
# [:] also shows in place expressions, not deferencing the variable.

Z = np.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 139644346715952
id(Z): 139644346715952


In [ ]:
# type conversion to numpy.

A = X.asnumpy()
B = np.array(A)
type(A), type(B)

(numpy.ndarray, mxnet.numpy.ndarray)

In [ ]:
# convert to python types

a = np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)

***2.2 Data Preprocessing***

In [ ]:
# utility function to create directories in the wanted address.
import os 
def mkdir_if_not_exist(path):
  """Make a directory if it does not exist."""
  # check if the path is a string.
  if not isinstance(path, str):
    path = os.path.join(*path)
  if not os.path.exists(path):
    os.makedirs(path)

In [ ]:
# create a dataset.
data_file='../data/house_tiny.csv'
mkdir_if_not_exist('../data')
with open(data_file, 'w') as f:
  f.write('NumRooms,Alley,Price\n') # Column names
  f.write('NA,Pave,127500\n') # Each row represents a data example
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')

In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [ ]:
# fill in the NaN values,
# hint that the categorical variables dont need to be filled.
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [ ]:
# create two seperate features for alley=pave and alley=nan
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [ ]:
# convert to numpy for further training, or tf.constant & torch.tensor in other frameworks.
from mxnet import np

X, y = np.array(inputs.values), np.array(outputs.values)
X, y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=float64),
 array([127500, 106000, 178100, 140000], dtype=int64))

***2.3 Linear Algebra***

In [ ]:
# ∈: means element of, like pythons 'in' statement.
# ⊂: means subset of. 

# scalar operations.
from mxnet import np, npx
npx.set_np()

x = np.array(3.0)
y = np.array(2.0)

x + y, x * y, x / y, x ** y

(array(5.), array(6.), array(1.5), array(9.))

In [ ]:
# vector
x = np.arange(4)
x

array([0., 1., 2., 3.])

In [ ]:
# matrix
A = np.arange(20).reshape(5, 4)
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [ ]:
# matrix transpose, (replacing rows and columns)
A.T

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [ ]:
# Special case: symmetric matrix, where the matrix and the transpose are equal.

B = np.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

array([[1., 2., 3.],
       [2., 0., 4.],
       [3., 4., 5.]])

In [ ]:
# pay attention to the diagonal.
B == B.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [ ]:
# reduction
x = np.arange(4)
x, x.sum()

(array([0., 1., 2., 3.]), array(6.))

In [ ]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(array([40., 45., 50., 55.]), (4,))

In [ ]:
A.sum(axis=[0, 1]) == A.sum()  # Same as `A.sum()`

array(True)

In [ ]:
# obvious.
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(array([ 8.,  9., 10., 11.]), array([ 8.,  9., 10., 11.]))

In [ ]:
sum_A = A.sum(axis=1, keepdims=True)

array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]])

In [ ]:
# culmucative sum.
A.cumsum(axis=0)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]])

In [ ]:
y = np.ones(4)
x, y, np.dot(x, y)

(array([0., 1., 2., 3.]), array([1., 1., 1., 1.]), array(6.))

In [ ]:
np.sum(x * y)

array(6.)

In [ ]:
# matrix multiplication
B = np.ones(shape=(4, 3))
np.dot(A, B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

In [ ]:
# norms
# l2 norm sqrt(sum(x**2))

u = np.array([3, -4])
np.linalg.norm(u)

array(5.)

In [ ]:
# l1 norm
# less senserive to outliers.

np.abs(u).sum()

array(7.)

In [ ]:
# fobenius norm (similar to that of the l2 norm for matrices).
np.linalg.norm(np.ones((4, 9)))

array(6.)

In [ ]:
np.abs(np.ones((4, 9))).sum()

array(36.)