In [ ]:
!pip install mxnet gluon d2l

In [1]:
from d2l import mxnet as d2l
from mxnet import autograd, np, npx
from mxnet.gluon import nn
npx.set_np()

In [2]:
def corr2d(X, K): #@save
  """Compute 2D cross-correlation."""
  h, w = K.shape
  # Compute output shape
  Y = np.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
  # loop over X and Y axes.
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      Y[i, j] = d2l.reduce_sum((X[i: i + h, j: j + w] * K))
  return Y

In [3]:
X = np.array([[0.0, 1.0, 2.0],
              [3.0, 4.0, 5.0],
              [6.0, 7.0, 8.0]])
K = np.array([[0.0, 1.0],
              [2.0, 3.0]])
corr2d(X, K)

array([[19., 25.],
       [37., 43.]])

In [4]:
class Conv2D(nn.Block):
  def __init__(self, kernel_size, **kwargs):
    super().__init__(**kwargs)
    self.weight = self.params.get('weight', shape=kernel_size)
    self.bias = self.params.get('bias', shape=(1,))
  def forward(self, x):
    return corr2d(x, self.weight.data()) + self.bias.data()

In [5]:
# Edge Detection
X = np.ones((6, 8))
X[:, 2:6] = 0
X

array([[1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.]])

In [6]:
K = np.array([[1.0, -1.0]])

In [7]:
Y = corr2d(X, K)
Y

array([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [8]:
corr2d(X.T, K)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])